### ISSUE TITLE
回馈广播接收不到

### ISSUE THREAD

**Issue by lzwzzy** [droneboost/airkiss_weixin#1]
回馈广播接收不到，wifi连接的时候有报错，请问，您的成功了吗？

**Comment by lzwzzy** [comment]
解决了

**Comment by droneboost** [comment]
不好意思，看到晚了。
已解决的话，Very good!

**Comment by lzwzzy** [comment]
大神，你最后的回馈广播是发送到了当前ip的广播地址了是吧，并不是全网发送（255.255.255.255）对吧？

**Comment by droneboost** [comment]
你好，时间长了有点忘了，应该不是硬编码的255.255.255.255， 而是设备通过微信配网成功获取IP地址之后，通过这个已获取IP地址的WiFi接口，取得它上面配置好的广播地址，再用那个广播地址去回馈的，具体查看checkIFip()这个函数内，是如何取得广播地址的处理。
